start:
	expo login
	sudo npm install --package-lock-only
	expo start

android:
	expo login
	sudo npm install --package-lock-only
	expo start --android

test:
	npm test
	
clean:
	rm -f -r node_modules
