start:
	expo login
	sudo npm install expo
	npm install expo-application
	expo install react-native-reanimated react-native-gesture-handler react-native-screens react-native-safe-area-context @react-native-community/masked-view
	npm install react-navigation
	npm install @react-navigation/stack
	expo start

clean:
	rm -f -r node_modules
