init: 
	sudo npm install --global expo-cli
	expo login
	sudo npm update
	sudo npm install 
	expo start

start:
	expo start

android:
	expo start --android

test:
	npm test
	
clean:
	rm -f -r node_modules
