name: Client Tests

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]
    paths: 
     - ./src/client/**
     - .github/workflows/JestClientTests.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Install Server Dependencies
        run: npm run setup
        working-directory: ./src/server/

      - name: Start Server
        run: node server &
        working-directory: ./src/server/

      - name: Install Client Dependencies
        run: npm install
        working-directory: ./src/client/
        
      - name: Client Tests
        run: npm test
        working-directory: ./src/client/
        
      - name: Shutdown Server
        run: pkill node
        working-directory: ./src/server/
